 # config file version
apiVersion: 1

 # list of datasources that should be deleted from the database
deleteDatasources:
   - name: "Elastic:northwind_orders*"
     orgId: 1


 # list of datasources to insert/update depending
 # on what's available in the database
datasources:
   # <string, required> name of the datasource. Required
 - name: "Elastic:northwind_orders*"
   # <string, required> datasource type. Required
   type: elasticsearch
   # <string, required> access mode. direct or proxy. Required
   access: proxy
   # <int> org id. will default to orgId 1 if not specified
   orgId: 1
   # <string> url
   url: elasticsearch:9200
   # <string> database name, if used
   database: "northwind_orders*"
   jsonData:
      timeField: "orderDate"
      esVersion: 70
   editable: true