 # config file version
apiVersion: 1

 # list of datasources that should be deleted from the database
deleteDatasources:
   - name: "Postgres:northwind:northwind"
     orgId: 1


 # list of datasources to insert/update depending
 # on what's available in the database
datasources:
   # <string, required> name of the datasource. Required
 - name: "Postgres:northwind:northwind*"
   # <string, required> datasource type. Required
   type: postgres
   # <string, required> access mode. direct or proxy. Required
   access: proxy
   # <int> org id. will default to orgId 1 if not specified
   orgId: 1
   # <string> url
   url: db
   #   # <string> database password, if used
   password: postgres
#   # <string> database user, if used
   user: postgres
   basicAuth: false
   # <string> database name, if used
   database: "northwind"
   jsonData:
      tlsAuth: false
      tlsAuthWithCACert: false
       
   editable: true